---

- name: deploy
  hosts: all
  vars:
    docroot: /var/www/virtual/{{ ansible_user }}/{{ lookup('env', 'DOMAIN') }}
  tasks:
    - name: create document root
      file:
        path: "{{ docroot }}"
        state: directory

    - name: copy HTML
      synchronize:
        src: "build/html/"
        dest: "{{ docroot }}/en"
        recursive: yes
        delete: yes

    - name: create .htaccess
      copy: 
        content: |
          RewriteEngine On
          RewriteCond %{HTTPS} !=on
          RewriteCond %{ENV:HTTPS} !=on
          RewriteRule .* https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L]
          RewriteRule ^$ /en/ [R]
        dest: "{{ docroot }}/.htaccess"

    - name: Correct Ownership of DocumentRoot
      file:
        path: "{{ docroot }}"
        state: directory
        recurse: yes
        mode: 0755
